language: java
dist: trusty

jdk:
- oraclejdk8

jobs:
  include:
  - arch: amd64
    dist: trusty
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-5
        - g++-5
        - yasm
        - binutils-2.26
    before_install:
    - scripts/replaceGcc.sh 5
    - scripts/replaceBinUtils.sh 2.26
  - arch: amd64
    dist: xenial
    jdk: openjdk8
  - arch: arm64
    dist: xenial
  - arch: ppc64le
    dist: xenial
  - arch: s390x
    dist: xenial

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc
    - g++
    - yasm
    - binutils
